### ISSUE TITLE
use.rawcode.txt file encoding & Model running

### ISSUE THREAD

**Issue by Matanpugach** [guxd/deep-code-search#10]
Hello, first of all you did impressive work!
I am using the pytorch version. I took all of the data in the google drive folder, unzipped all files and replaced the files in \data\github with them. 
I have several questions:
1. Is the model already trained ? (can i simply run _python codesearcher.py --mode search_ or should i train the model first)
2. Does the file _use.codevecs.normalized.h5_ already existing in the \data\github matches the full data files from google drive?
3. While running  _python codesearcher.py --mode search_  i receive the following error (when using the use.rawcode.txt from google drive):
![image](https://user-images.githubusercontent.com/27849930/49163480-d9effc80-f335-11e8-90b2-1fe850e5f3f2.png)
Is the use.rawcode.txt file from the google drive folder not encoded in utf-8?

**Comment by guxd** [comment]
Hi, thanks for your interest!

1. The model is not trained
2. They do not match, you should generate a normalized vector h5 file for the large dataset
3. It may contain some unrecognized characters, you can refer to the keras version about how to read the codebase.

**Comment by Matanpugach** [comment]
Thanks for the response @guxd! Is there a way of receiving the trained model?

**Comment by guxd** [comment]
We did not keep the trained model.

**Comment by Matanpugach** [comment]
@guxd is the data encoded in utf-8? i still recieve the following error:
```
Traceback (most recent call last):
  File "codesearcher.py", line 450, in <module>
    codesearcher.load_codebase()
  File "codesearcher.py", line 89, in load_codebase
    codes=codecs.open(self.path+self.data_params['use_codebase']).readlines()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 5538-5539: invalid continuation byte
```

**Comment by Matanpugach** [comment]
if it is in utf-8, i transformed the open call from line 90 from:
`codes=codecs.open(self.path+self.data_params['use_codebase']).readlines()`
to:
`codes=codecs.open(self.path+self.data_params['use_codebase'],encoding='utf8',errors='replace').readlines()`

**Comment by guxd** [comment]
Thanks for the correction!
