### ISSUE TITLE
MRR Calculations

### ISSUE THREAD

**Issue by matanpugach** [guxd/deep-code-search#14]
How was the MRR calculated on the 50 examples in the results.xlsx? Do you have perhaps a script of the calculation? What file was used as the search base for the analysis of those 50 examples?

**Comment by guxd** [comment]
could you please check your email (perhaps in the spams) for my replies to your questions?

**Comment by guxd** [comment]
The MRR for the 50 examples are calculated manually according to the results in Table 
Section 4.3 presents the search base

**Comment by matanpugach** [comment]
@guxd it was in the spam folder. Thanks!

**Comment by guxd** [comment]
Please refer to the Equation 15 in the paper for the MRR calculation.
