### ISSUE TITLE
Keras model data usage

### ISSUE THREAD

**Issue by matanpugach** [guxd/deep-code-search#15]
Hello!

I admire the work you did in this paper and have several questions regarding the data partitioning and the way the model uses it. Mainly because each time i re-run the model searching script, i get different top results.
1. Regarding the files starting with ‘train.’ -  The amount of examples sampled from it is 80k every epoch, is this correct? I wanted also to make sure this the data the model trains on? how many examples does it contain? 

2.	Regarding the files starting with ‘test.’-  What is it used for (is it for validation)? Is the usage from it is also sampled ( the data is not used entirely each time) ? how many examples does it contain?

3.	Regarding the files starting with ‘use.’ – Is it the base for running the search queries? Is the usage from it is sampled (i.e., Is a subset of it is used every time)? how many examples does it contain? 

4.	Is there an intersection\subset relation between any of the train.\test.\use. files content?

**Comment by guxd** [comment]
The train and test data has intersection. Both contain code with comments.

**Comment by matanpugach** [comment]
@guxd what is the intersection? is there an subset relation\inclusion between the two?
