### ISSUE TITLE
Training Data question

### ISSUE THREAD

**Issue by ttbuffey** [guxd/deep-code-search#19]
Dear Colleague,

For the training data, I want to ask where do you get the descriptions for each code snippets from GitHub.  Are the description extracted from the GitHub code comments? 
If so, How do you extract the simplified description from the comments?

**Comment by guxd** [comment]
Yes, the descriptions are extracted from the code comments specifically the first sentence of doc comments. Please refer to Section 4.1 in our paper for the extraction.

**Comment by ttbuffey** [comment]
Thanks for your answering. The paper is of great value for me.
I have a basic understanding of the data pre-processing, download java projects from Github, then extract all the java methods from projects, finally extract description, API sequence, method name, Tokens for each method.
Can you provide the source code of data pre-processing for reference. Thanks very much.

**Comment by ttbuffey** [comment]
@guxd 请问你有数据预处理的代码吗（下载Github代码，提取函数中的description，API sequence，method， Token）？可以share给我吗？
