### ISSUE TITLE
Questions on Prescion@k with "relevant results"

### ISSUE THREAD

**Issue by ZhaoYi1031** [guxd/deep-code-search#22]
I am wondering about the "relevant results", does that mean for every StackOverflow question, when we label the data, we need to collect several **relevant results**? Othervise how to mark the returned k results as relevant or not? (Beacuse before for every question I only chose the most relevant result, so I am quite confused with the Precision@k metric.) Thx a lot.

**Comment by guxd** [comment]
For each question, we return K results and manually check how many of them are relevant to the question.

**Comment by ZhaoYi1031** [comment]
Ok. It apperas to me that it maybe to distinguish whether it is relevant. (In my opinion, we can only judge in the syntactic angle while we build a model based on the semantic information.
