### ISSUE TITLE
result relevant for larger code base and small code base

### ISSUE THREAD

**Issue by dtfinder** [guxd/deep-code-search#25]
Hi, 
Based on the larger corpus 18,233,872 keras training model , I did two kind code search based small codebase and larger codebase. 
1)the larger codebase search is based on the same use.data from google drive. 
2)the small codebase search is based on the default 10000 use.data from git code.

I use the Query from Table 1 in the paper, I find the search result from 1) has higher similar value than 2), but we can find more relevant result from 2) than 1) in the top 5 result.  

For example:
I input "convert string to date"
2) can get the the result such as ("public static Date convertStringToDate"  , 0.41653952)
1) get the result such as ("private booolean fileHasValidIdentifier" .... 0.43153855)

I think 1) has about 1000 times code items than 2),  and 1) is very difficult to let more relevant code appeared in the top 5 result with similar value sort.

Do you meet the above result?

**Comment by guxd** [comment]
the provided small dataset is not useful. It is just a demo for quick setup.
