### ISSUE TITLE
Question: are use.methname.h5, use.tokens.h5, use.apiseq.h5 generated by processing use.rawcode.txt?

### ISSUE THREAD

**Issue by JoeQiao666** [guxd/deep-code-search#26]

**Comment by guxd** [comment]
yes

**Comment by ttbuffey** [comment]
Hi @guxd,

I see the .h5 files contains two keys, "indices" and "phrases", Can you help to tell me what do they mean? Does indices means the index 0 to 9999 for 10000 records, phrases mean the real data?

Do you transform the use.tokens.txt file to .h5 file, can you explain a bit about the process, if raw code is provide, it will be awesome.

**Comment by ttbuffey** [comment]
Do you have the source code of generating .h5 file, I'm not sure about the detailed parameters of creating a hdf dataset.

**Comment by ttbuffey** [comment]
Dear Author,

As I'm new in hdf, I opened the use.methname.h5 file with HDFView, I can check the hdf dataset has two attributes, "indices" and "phrases".
![Screen Shot 2019-05-12 at 9 18 30 PM](https://user-images.githubusercontent.com/7931810/57582791-9f50d980-74fb-11e9-8fa7-cc7e0a684f74.png)
For indices, I can open the contents, for phrases there is error when opening it. I can't see the contents of phrases.
But by debugging into the code, I find phrases is a list of numbers repenting the method names, e.g. [82, 31, 262, 1212, 176], which means ['contains', "key", "store", "registry", "context"] respectively. 
I want to ask how the strings are transformed into the according numbers?

- My  first assumption is when creating the HDF datasets, the strings are set as input dataset, This  is this done by some compression settings and save them as numbers?
a = ['contains', "key","store","registry","context"]
dataset=h5.create_dataset("phrases", data=a) 

- My second assumption is the strings are transformed to numbers at first and then set as HDF dataset.

Could you please tell me the right process, and how strings are transformed to numbers。

Thanks a lot for your continuous help.

Best Regards,
ttbyffey
