### ISSUE TITLE
keras model with python2.7 have problem when dealing prediction input

### ISSUE THREAD

**Issue by fp-magic** [guxd/deep-code-search#27]
Keras model with python2.7, mode 'search', in 'Input query: ' would lead to 'SyntaxError: unexpected EOF while parsing' with whatever string input.
I do not find the reason behind, but python3.5 do not have such problem.

**Comment by guxd** [comment]
could you show the full stack trace for this error?

**Comment by guxd** [comment]
python 2.7 is no longer supported.
