### ISSUE TITLE
How come the contents of "phrases" in use.methname.h5 file

### ISSUE THREAD

**Issue by ttbuffey** [guxd/deep-code-search#28]
Dear Author,

As I'm new in hdf, I opened the use.methname.h5 file with HDFView, I can check the hdf dataset has two attributes, "indices" and "phrases".
![Screen Shot 2019-05-12 at 9 18 30 PM](https://user-images.githubusercontent.com/7931810/57582791-9f50d980-74fb-11e9-8fa7-cc7e0a684f74.png)
For indices, I can open the contents, for phrases there is error when opening it. I can't see the contents of phrases.
But by debugging into the code, I find phrases is a list of numbers repenting the method names, e.g. [82, 31, 262, 1212, 176], which means ['contains', "key", "store", "registry", "context"] respectively. 

I want to ask how the strings are transformed into the according numbers? what's their relationship.

Thanks a lot for your continuous help.

Best Regards,
ttbyffey

**Comment by guxd** [comment]
They are translated by replacing strings with corresponding ids in the vocabulary.

**Comment by ttbuffey** [comment]
@guxd I understand this now. But how come the vocab.methname.pkl file, how come the relationships of the key and values in this file? 

Thanks very much for your quick response.
Best Regards,
Phoebe

**Comment by ttbuffey** [comment]
Is there no special relationship between key and value in vocab.methname.pkl file?
We only need to make sure each token has a unique represented ID

**Comment by guxd** [comment]
The vocabulary is a mapping of tokens to ids.  We rank the tokens according to their frequencies and set the id for each token as their rank.

**Comment by ttbuffey** [comment]
Thank for your response. Sorry to bother you so many time, we are trying to replace the search codebase with our own, and test based on your trained-model, so we have many questions when reimplementing some process.

I have another question, are the tokens in vocab.methname.pkl file only extracted from **training source code?**
Does it contain tokens in **search code base**?

**Comment by guxd** [comment]
No, it doesn't. Any unseen tokens in the search code base will be recognized as UNK.

**Comment by ttbuffey** [comment]
Thx very much
