### ISSUE TITLE
One question about training time with tensorflow keras mode.

### ISSUE THREAD

**Issue by dtfinder** [guxd/deep-code-search#29]
Hi, Guxd
I tried to training the model with Tensorflow Keras. 
I used the default setting from github repo without any change on one Nivida GTX 1080, or on one AWS K80. 
For the default data, (small data with 10000 item), I find it is need about 4~5 minutes to finish one epoch, If I need to do 500 epochs, the whole training need about 33~50 hours,  the training time is very close as your paper statement for training on K40 with 50 hours. 
But if I used the larger train data from google driver( about 1800 times larger than default data), I find it is impossible to finish the training on one K40 withing 50 hours. 

My question is if your trained model on google driver is based on larger data,
or if I need to do other sitting for the configs.py or change the code of the model.py and main.py, and I can finish the larger data training within 50 hours.

BR

**Comment by guxd** [comment]
The number of epochs in our paper was calculated as in a subset of the whole dataset (around 10000 items).  The real number of epochs was around 3.

**Comment by dtfinder** [comment]
Thank you for your clear answer.
