### ISSUE TITLE
One question about pre-processing for input query string

### ISSUE THREAD

**Issue by dtfinder** [guxd/deep-code-search#34]
Hi, Xiaodong
Do you do some pre-processing for the input query string?
I use the input string from benchmark queries from your paper Table 1. I found if I do some suitable process for the input string, the search step can return more related result, but it is not easy to do this kind pre-processing. 

For example:
Input Query: "how do I invoke a java method when given the method name as a string", 
-------this input query return no much related result in 5 return search results.

but as input queries as following:
Input Query: "invoke a java method when given the method name as a string"
-------this input query return 1 related result in 5 return search results.
Input Query: "invoke a java method when given the method name"
-------this input query return 2 related result in 5 return search results.
------- maybe 2 best from my view. 

Input Query: "invoke method when given the method name"
-------this input query return 2 related result in 5 return search results.
Input Query: "invoke method given method name"
-------this input query return 2 related result in 5 return search results.

From my understanding for your paper and code, after the training and repo steps, the search step is just comparing the input query vector distance with vectors from repo. because the vectors from repo are fixed, to get the better search result, the input query become a key element, if input query include more words such as "how" "do" "in" "as"  "a" "string", these function words deeply effect the result, and hidden more related result for notional words such as "invoke".  I don't know if you have a good way to balance the pre-processing for the input query input. 

BR

**Comment by ttbuffey** [comment]
I also have a similar question, does the rank of a word in the vocab file affect its search performance?

**Comment by guxd** [comment]
Hi, very good question! 
Query preprocessing is important since queries are different from descriptions in the training set.  
We used the following preprocessing rules:
"how to XXX" -> "XXX"
"how do I XXX" -> "XXX"
"how can I XXX" -> "XXX"
"what is the best way to XXX" -> "XXX"
There is no good way to balance the preprocessing but I think the above rules cover most queries in the real world code search scenario.
 More rules can be designed to achieve better performance.

**Comment by guxd** [comment]
@ttbuffey I think the rank does not affect the performance since we did not consider word rank in the model. All words are embedded equally.

**Comment by ttbuffey** [comment]
@guxd i also have another question, If one word in the query is not included in any vocab files, but included in search codebase. Will this decrease the search performance?

**Comment by guxd** [comment]
In that case, yes. Because the word will be converted as an unknown word (UNK token).
