### ISSUE TITLE
Training on Pytorch: NameError: name 'dims' is not defined

### ISSUE THREAD

**Issue by 975935259** [guxd/deep-code-search#40]
Sorry, I have a question.
Maybe I did something wrong.
I tried for many times and failed in same way.

from collections import Mapping, defaultdict
[nltk_data] Downloading package punkt to /home/blx/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
loading data...
18223872 entries
loading data...
10000 entries
Constructing Model..
epo:[1/5] itr:[0/284748] step_time:1s Loss=0.49624
epo:[1/5] itr:[100/284748] step_time:3s Loss=0.49965
epo:[1/5] itr:[200/284748] step_time:3s Loss=0.49992
epo:[1/5] itr:[300/284748] step_time:3s Loss=0.49965
epo:[1/5] itr:[400/284748] step_time:3s Loss=0.49847
epo:[1/5] itr:[500/284748] step_time:3s Loss=0.49712
epo:[1/5] itr:[600/284748] step_time:3s Loss=0.49503
epo:[1/5] itr:[700/284748] step_time:3s Loss=0.48588
epo:[1/5] itr:[800/284748] step_time:3s Loss=0.44364
epo:[1/5] itr:[900/284748] step_time:3s Loss=0.38405
epo:[1/5] itr:[1000/284748] step_time:3s Loss=0.35486
epo:[1/5] itr:[1100/284748] step_time:3s Loss=0.33373
epo:[1/5] itr:[1200/284748] step_time:3s Loss=0.31694
epo:[1/5] itr:[1300/284748] step_time:3s Loss=0.30157
epo:[1/5] itr:[1400/284748] step_time:3s Loss=0.28955
epo:[1/5] itr:[1500/284748] step_time:3s Loss=0.27922
epo:[1/5] itr:[1600/284748] step_time:3s Loss=0.27275
epo:[1/5] itr:[1700/284748] step_time:3s Loss=0.25574
epo:[1/5] itr:[1800/284748] step_time:3s Loss=0.25097
epo:[1/5] itr:[1900/284748] step_time:3s Loss=0.24439
epo:[1/5] itr:[2000/284748] step_time:3s Loss=0.24494
epo:[1/5] itr:[2100/284748] step_time:3s Loss=0.23787
epo:[1/5] itr:[2200/284748] step_time:3s Loss=0.22471
epo:[1/5] itr:[2300/284748] step_time:3s Loss=0.22553
epo:[1/5] itr:[2400/284748] step_time:3s Loss=0.20872
epo:[1/5] itr:[2500/284748] step_time:3s Loss=0.20546
epo:[1/5] itr:[2600/284748] step_time:3s Loss=0.20387
epo:[1/5] itr:[2700/284748] step_time:3s Loss=0.19426
epo:[1/5] itr:[2800/284748] step_time:3s Loss=0.18942
epo:[1/5] itr:[2900/284748] step_time:3s Loss=0.19045
epo:[1/5] itr:[3000/284748] step_time:3s Loss=0.18208
epo:[1/5] itr:[3100/284748] step_time:3s Loss=0.18582
epo:[1/5] itr:[3200/284748] step_time:3s Loss=0.17979
epo:[1/5] itr:[3300/284748] step_time:3s Loss=0.17698
epo:[1/5] itr:[3400/284748] step_time:3s Loss=0.17425
epo:[1/5] itr:[3500/284748] step_time:3s Loss=0.16560
epo:[1/5] itr:[3600/284748] step_time:3s Loss=0.16273
epo:[1/5] itr:[3700/284748] step_time:3s Loss=0.16250
epo:[1/5] itr:[3800/284748] step_time:3s Loss=0.15530
epo:[1/5] itr:[3900/284748] step_time:3s Loss=0.15151
epo:[1/5] itr:[4000/284748] step_time:3s Loss=0.15246
epo:[1/5] itr:[4100/284748] step_time:3s Loss=0.15054
epo:[1/5] itr:[4200/284748] step_time:3s Loss=0.15059
epo:[1/5] itr:[4300/284748] step_time:3s Loss=0.14527
epo:[1/5] itr:[4400/284748] step_time:3s Loss=0.14572
epo:[1/5] itr:[4500/284748] step_time:3s Loss=0.14195
epo:[1/5] itr:[4600/284748] step_time:3s Loss=0.13322
epo:[1/5] itr:[4700/284748] step_time:3s Loss=0.13429
epo:[1/5] itr:[4800/284748] step_time:3s Loss=0.12924
epo:[1/5] itr:[4900/284748] step_time:3s Loss=0.12834
validating..
100%|██████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.26s/it]
  0%|                                                                          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 248, in <module>
    train(args)
  File "train.py", line 124, in train
    acc1, mrr, map1, ndcg = validate(valid_set, model, 10000, 1)  
  File "train.py", line 206, in validate
    sims = np.squeeze(dims, axis=1)
NameError: name 'dims' is not defined
Closing remaining open files:./data/github/train.tokens.h5...done./data/github/valid.apiseq.h5...done./data/github/train.apiseq.h5...done./data/github/valid.name.h5...done./data/github/train.name.h5...done./data/github/valid.desc.h5...done./data/github/train.desc.h5...done./data/github/valid.tokens.h5...done

**Comment by guxd** [comment]
please rename 'dims' to 'sims'

**Comment by 975935259** [comment]
thank you!

**Comment by guxd** [comment]
fixed in the new commit
