### ISSUE TITLE
Pytorch search FileNotFoundError

### ISSUE THREAD

**Issue by 975935259** [guxd/deep-code-search#41]
Hi, Xiaodong Gu!
I successfully completed the training and the word embedding yesterday.
But when I ran the "python search.py --model JointEmbeder"
The Error came as follows:
from collections import Mapping, defaultdict
Constructing Model..
Traceback (most recent call last):
  File "search.py", line 109, in <module>
    model.load_state_dict(torch.load(ckpt, map_location=device))
  File "/home/blx/.local/lib/python3.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './output/JointEmbeder/github/models/epo-1.h5'

Then I opened the search.py and found.

parser.add_argument('--reload_from', type=int, default=-1, help='epoch to reload from')
…………
if __name__ == '__main__':
    args = parse_args()
    device = torch.device(f"cuda:{args.gpu_id}" if torch.cuda.is_available() else "cpu")
    config=getattr(configs, 'config_'+args.model)()
    
    ##### Define model ######
    logger.info('Constructing Model..')
    model = getattr(models, args.model)(config)#initialize the model
    ckpt=f'./output/{args.model}/{args.dataset}/models/epo{args.reload_from}.h5'
…………
The default value of "--reload from" is -1, but the file in './output/JointEmbeder/github/models/' is "epo10000.h5","epo20000.h5","epo30000.h5",etc

So how should I change the code to make it work?
Thank you very much!

**Comment by guxd** [comment]
please run it by `python search.py --model JointEmbedder --reload_from 2000000` where 2000000 refers to the number of steps you have trained.

**Comment by 975935259** [comment]
Could I know how much memory is needed to run the search.py?
My memory size is 32G but the process is killed because of out-of-memory.

**Comment by guxd** [comment]
64G is definitely enough

**Comment by guxd** [comment]
You can consider a lazy load of raw code to save memory.
