### ISSUE TITLE
Search on pytorch AssertionError: inconsistent number of chunks, check whether the specified files for codebase and code vectors are correct!

### ISSUE THREAD

**Issue by BigMax-Jason** [guxd/deep-code-search#42]
In the repr_code.py:
###
parser.add_argument('--chunk_size', type=int, default=2000000, help='split code vector into chunks and store them individually. '\
###
In the search.py:
###
parser.add_argument('--chunk_size', type=int, default=2000000, help='codebase and code vector are stored in many chunks. '\
###
The values are the same.
When I ran "python search.py --model JointEmbeder --reload_from 1420000", it went wrong. (It's 1420000 because in the /output/JointEmbeder/github/models I have 142 files from "epo10000.h5" to "epo 1420000.h5")
What's wrong? Thank you!

**Comment by guxd** [comment]
can you check all `./data/github/use.codevecs_partX.h5` files (where Xs' are numbers).
Then what is the maximum number of X? Is X equal to Y%chunk_size+1 where Y is the number of lines of 'use.rawcode.txt'?

**Comment by BigMax-Jason** [comment]
I have checked it.
X=1626
chunk_size=100000 (I tried last time)
Y=10000
But why the number of lines of 'use.rawcode.txt' is equal to the number of lines of 'test.rawcode.txt'?
They are all 10000.

**Comment by BigMax-Jason** [comment]
I have checked it.
X=1626
chunk_size=100000 (I tried last time)
Y=10000

**Comment by guxd** [comment]
Did you replace the 'use.rawcode.txt' with the data in Google Driver?

**Comment by BigMax-Jason** [comment]
Sorry, I downloaded the data in Google Driver but I didn't find the 'use.rawcode.txt'.
I will download it again.

**Comment by guxd** [comment]
It is located in the keras folder.
