### ISSUE TITLE
What role do  '<s>' and '</s>' label play in the vocabulary?

### ISSUE THREAD

**Issue by liubinbin0032** [guxd/deep-code-search#44]
I understand the '\<pad\>' and '\<unk\>' label in the vocabulary. But what's the use of '\<s\>' and '\</s\>' label? Do you add '\<s\>' and '\</s\>' label at the beginning and the end of each sentence in the training set? I found there exit '\</s\>' label in the api_seq sentence.

**Comment by guxd** [comment]
Yes, they represent the beginning and the end of each sequence.
