### ISSUE TITLE
about eval func

### ISSUE THREAD

**Issue by BGMpool2014** [guxd/deep-code-search#46]
def eval(self, model, poolsize, K):
        def ACC(real,predict):
            sum=0.0
            for val in real:
                try: index=predict.index(val)
                except ValueError: index=-1
                if index!=-1: sum=sum+1  
            return sum/float(len(real))
        def MAP(real,predict):
            sum=0.0
            for id,val in enumerate(real):
                try: index=predict.index(val)
                except ValueError: index=-1
                if index!=-1: sum=sum+(id+1)/float(index+1)
            return sum/float(len(real))
        def MRR(real,predict):
            sum=0.0
            for val in real:
                try: index=predict.index(val)
                except ValueError: index=-1
                if index!=-1: sum=sum+1.0/float(index+1)
            return sum/float(len(real))
        def NDCG(real,predict):
            dcg=0.0
            idcg=IDCG(len(real))
            for i,predictItem in enumerate(predict):
                if predictItem in real:
                    itemRelevance=1
                    rank = i+1
                    dcg+=(math.pow(2,itemRelevance)-1.0)*(math.log(2)/math.log(rank+1))
            return dcg/float(idcg)
        def IDCG(n):
            idcg=0
            itemRelevance=1
            for i in range(n):
                idcg+=(math.pow(2,itemRelevance)-1.0)*(math.log(2)/math.log(i+2))
            return idcg

        if self._eval_sets is None:
            methnames,apiseqs,tokens,descs=self.load_valid_data_chunk(poolsize)
            self._eval_sets=dict()
            self._eval_sets['methnames']=methnames
            self._eval_sets['apiseqs']=apiseqs
            self._eval_sets['tokens']=tokens
            self._eval_sets['descs']=descs
        acc,mrr,map,ndcg=0,0,0,0
        data_len=len(self._eval_sets['descs'])
        for i in range(data_len):
            desc=self._eval_sets['descs'][i]#good desc
            descs=self.pad([desc]*data_len,self.data_params['desc_len'])
            methnames=self.pad(self._eval_sets['methnames'],self.data_params['methname_len'])
            apiseqs=self.pad(self._eval_sets['apiseqs'],self.data_params['apiseq_len'])
            tokens=self.pad(self._eval_sets['tokens'],self.data_params['tokens_len'])
            n_results = K          
            sims = model.predict([methnames, apiseqs,tokens, descs], batch_size=data_len).flatten()
            negsims=np.negative(sims)
            predict=np.argsort(negsims)#predict = np.argpartition(negsims, kth=n_results-1)
            predict = predict[:n_results]   
            predict = [int(k) for k in predict]
            real=[i]
            acc+=ACC(real,predict)
            mrr+=MRR(real,predict)
            map+=MAP(real,predict)
            ndcg+=NDCG(real,predict)                          
        acc = acc / float(data_len)
        mrr = mrr / float(data_len)
        map = map / float(data_len)
        ndcg= ndcg/ float(data_len)
        logger.info('ACC={}, MRR={}, MAP={}, nDCG={}'.format(acc,mrr,map,ndcg))
        return acc,mrr,map,ndcg
请问一下你的eval函数是不是有问题阿？  real每次循环都是一个数据集real=[i](记录数据的索引位置)，但是你的mrr map函数集都是 return sum/float(len(real))。real的长度总是1.
但是我的理解应该是一个desc对应多个real的数据列表作为ground-truth数据。你这里这个eval函数可以解释一下么？

**Comment by guxd** [comment]
一个desc只有一个real作为ground-truth, 使用len(real)是为了兼容batch的情形
