### ISSUE TITLE
About Dataset.

### ISSUE THREAD

**Issue by TomasAndersonFang** [guxd/deep-code-search#52]
您好，看到您的给的数据集里有个use.rawcode.h5文件，不知道是不是原始代码。如果是的话我发现这个代码的数量只有1600w+，而您给的train.desc.h5文件中desc的数量有1800w+，请问您能说明一下use.rawcode.h5这个文件是什么嘛？
![image](https://user-images.githubusercontent.com/38727343/92677681-f4526900-f356-11ea-8092-94161125217d.png)

**Comment by guxd** [comment]
use.rawcode.h5是测试数据，不是用来训练的。对应其他以use开头的文件。

**Comment by TomasAndersonFang** [comment]
> use.rawcode.h5是测试数据，不是用来训练的。对应其他以use开头的文件。

十分感谢您的回复。
