### ISSUE TITLE
After training, the model search results do not match the query

### ISSUE THREAD

**Issue by CreateTao** [guxd/deep-code-search#59]
I followed the steps described in the readme.md in the PyTorch file to implement each step.
1、The training data was downloaded from GDrive
2、"Python repr_code.py --model JointEmbeder --reload_from XXX" and "python search.py --model JointEmbeder --reload_from. I used 4000000 for "XXX".
3、torch==1.6.0 and torchversion==0.7.0
But the result of the final query did not meet the conditions，Is there a condition missing from my procedure

**Comment by guxd** [comment]
There is a severe bug in the current PyTorch implementation:
The embedding vector for a query just varies with the batch size (the batch size for a query in search.py  is always 1, but increasing it will result in different query vectors...)
We guess that the bug originates from the `SeqEncoder` class in modules.py.
Unfortunately, we haven't pinpointed the exact reason.
If you have any clues about this bug, please help.

**Comment by guxd** [comment]
We have fixed the bug, uncomment `h_n = h_n.transpose(1, 0).contiguous()`
