### ISSUE TITLE
download pretrained model

### ISSUE THREAD

**Issue by skye95git** [guxd/deep-code-search#61]
Hi, the URL of the pretrained model is invalid. Can you provide the URL again? Thanks.

**Comment by guxd** [comment]
Have updated, please check.

**Comment by zhangyue-se** [comment]
> Have updated, please check.

Hello，I wonder how many epochs the trained model has run？Is it the 500 epochs mentioned in the paper?

**Comment by guxd** [comment]
The 500 epochs mentioned in the paper means Keras epochs (in the Keras version).
In the PyTorch version we trained the model for 4,000,000 iterations.
