### ISSUE TITLE
Problem in the Kears Version

### ISSUE THREAD

**Issue by zhangyue-se** [guxd/deep-code-search#63]
Hello, in the Keras version, are the files in the data/github/ folder trained? Can I search directly? Or do I need to download the data set and retrain?

I tried to use the files under GitHub to search directly, but the results were not very good, the similarity was less than 0.1:
![image](https://user-images.githubusercontent.com/46780077/125398540-0ae7a780-e3e2-11eb-9beb-11ca2302c00f.png)

**Comment by zhangyue-se** [comment]
> The files in the folder are only provided for model setup.
> You should download the dataset and retrain, or you can use the pre-trained model from Google drive.

Thank you for your help. I have already started training the model.
I'm also running the PyTorch version. Is that step4000000.h5 trained using the big data set in Google Drive?

**Comment by guxd** [comment]
Yes, it was trained using the big data set in Google Drive.
