### ISSUE TITLE
How to get Java methods from Java source ﬁles or Java projects?

### ISSUE THREAD

**Issue by skye95git** [guxd/deep-code-search#64]
I want to collect more corpus according to the method in the paper. Section 4.1 'Collecting Training Corpus' of the paper describes "We build the training tuples using Java methods that have documentation comments from open-source projects on GitHub". I can get the Java projects or Java source ﬁles from github. But there are a lot of things in a Java file, such as import and functions. How can I divide them into code snippets? When you collect the training corpus, you divide it manually?

**Comment by CaptainDredge** [comment]
You can use any famous Java code parser and the traverse the Abstract Syntax tree maintaining a state and filtering according to your conditions for eg. `Give me a function preceded by a comment`

**Comment by CaptainDredge** [comment]
If you're making something cool on code search or publishing something I can tag along and help as much as I can

**Comment by skye95git** [comment]
> You can use any famous Java code parser and the traverse the Abstract Syntax tree maintaining a state and filtering according to your conditions for eg. `Give me a function preceded by a comment`

Thank you very much! I will try it.

**Comment by skye95git** [comment]
The author has tell me the method in email. They parsed the source folder of each project using GrouMiner.

Tung T. Nguyen, Hoan A. Nguyen, Nam H. Pham, Jafar M. Al-Kofahi, Tien N. Nguyen, "Graph-based Mining of Multiple Object Usage Patterns", in Proceedings of the 17th ACM SIGSOFT Symposium on the Foundations of Software Engineering (ACM ESEC/FSE 2009), August 24-28, 2009. ACM Press, 2009.

I also find other methods, such as  TreeSitter in paper `CodeSearchNet Challenge Evaluating the State of Semantic Code Search`.
I will try it.
