### ISSUE TITLE
Questions about the dataset.

### ISSUE THREAD

**Issue by AlphaDoraem** [guxd/deep-code-search#75]
您好，我运行了pytorch版本的train.py，但是出现了以下错误，在/data/github/目录下并没有valid.apiseq.h5等文件，请问是哪里出了问题？怎么解决呢？
OSError: ``./data/github/valid.apiseq.h5`` does not exist

**Comment by li-car-fei** [comment]
您好，数据集里只用train部分的rawcode.txt
可以将test部分的rawcode.txt分享一下吗？
