### ISSUE TITLE
Evaluation benchmark dataset top 50 manually inspected relevance labels?

### ISSUE THREAD

**Issue by Laksh47** [guxd/deep-code-search#8]
Hi @guxd 

It is mentioned in the paper that two developers manually labelled relevant/non-relevant results for the top 50 stackoverflow questions used as benchmark.

I see the 50 queries are available in the paper. Could you please the corresponding manually labelled relevant/non relevant snippets for each query?

Thanks,
Laksh

**Comment by guxd** [comment]
please check it in the keras/results/ folder
